import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1280,height:900} });
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,150))}); p.on('pageerror',e=>errs.push('PE '+e.message.slice(0,150)));
await p.goto('https://modu-baekje.vercel.app/ko/places',{waitUntil:'networkidle',timeout:60000});
await p.waitForTimeout(2000);
const over = await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
const imgs = await p.evaluate(()=>[...document.images].map(i=>i.naturalWidth));
console.log('h-overflow', over, 'images', imgs.length, 'decoded', imgs.filter(w=>w>0).length);
await p.screenshot({path:'/tmp/claude-1000/-home-mark-minipc-workspace-tour-data/06678fdb-4787-477d-bb58-61048ef29645/scratchpad/prod-places.png', fullPage:true});
await p.goto('https://modu-baekje.vercel.app/ko/places/gongsanseong/docent',{waitUntil:'networkidle',timeout:60000});
const audio = await p.evaluate(async()=>{const a=document.querySelector('audio'); if(!a) return 'none'; a.preload='auto'; a.load();
  return await new Promise(r=>{a.addEventListener('loadedmetadata',()=>r('ok '+a.duration),{once:true}); a.addEventListener('error',()=>r('error'),{once:true}); setTimeout(()=>r('timeout'),12000);});});
console.log('audio', audio);
console.log('ERRORS', [...new Set(errs)].slice(0,6));
await b.close();
